### ISSUE TITLE
Corrigir erros no componentes

### ISSUE THREAD

**Issue by diogoodiego** [tads-cnat/ifsolve#140]
**Tempo previsto (em horas):** 20 horas

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):** Média

**Qualidade (baixa | média | alta):**

**Descrição**
Corrigir erros apontados pelo Eslint.

**Comment by Livia-Rachell** [comment]
Erro `jsx-a11y/label-has-associated-control` não resolvido em `src/pages/criarItem`, na linha 194.

@diogoodiego @IsraelKleber
