### ISSUE TITLE
Destacar feedback de input obrigatório na criação de avaliação

### ISSUE THREAD

**Issue by alcides07** [tads-cnat/ifsolve#148]
**Tempo previsto (em horas):** *<1*

**Tempo gasto (em horas):** *?*

**Complexidade (baixa | média | alta):** *baixa*

**Qualidade (baixa | média | alta):** *?*

**Descrição:** 
O texto que informa que um determinado input é obrigatório na criação de uma avaliação está na cor preta e sem destaque algum em meio a outras informações do formulário.
Se basear em como está a estilização desse tipo de feedback na tela de criação de um item.

**Comment by Livia-Rachell** [comment]
`Erros` encontrados durante a correção:
- Consigo criar uma avaliação sem questões;
- Ao selecionar uma alternativa correta, a palavra "Alternativa" fica colada com a letra da alternativa.
