### ISSUE TITLE
Resolver erros encontrados pelo sonarcloud

### ISSUE THREAD

**Issue by IsraelKleber** [tads-cnat/ifsolve#181]
**Tempo previsto (em horas): 20**

**Tempo gasto (em horas):**

**Complexidade (baixa | média | alta): média**

**Qualidade (baixa | média | alta):**

**Descrição**

**Comment by matRaph** [comment]
![image](https://github.com/tads-cnat/ifsolve/assets/42880393/e42c0b28-94d3-4fd8-86cf-0256f6558c8e)

Esse foi o único problema de segurança relevante encontrado, considerando que os outros erros detectados estavam no seeder do backend, utilizado apenas para testes.
